### ISSUE TITLE
[issue] pnpm dev 启动失败

### ISSUE THREAD

**Issue by locustbaby** [honghuangdc/soybean-admin#142]
```
root@dev:~/soybean-admin# npm -v
6.14.17
root@dev:~/soybean-admin# pnpm -v
7.13.5
root@dev:~/soybean-admin# node -v
v14.20.1
root@dev:~/soybean-admin# pnpm dev

> soybean-admin@0.9.6 dev /root/soybean-admin
> cross-env VITE_SERVICE_ENV=dev vite

                                                                                                                        14:56:05
  VITE v3.1.7  ready in 2753 ms

  ➜  Local:   http://localhost:5173/                                                                                    14:56:05
  ➜  Network: http://192.168.0.104:5173/                                                                                14:56:05
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:5173/' ]
}
 ELIFECYCLE  Command failed with exit code 1.
```
版本如上，启动失败，端口也没占用

**Comment by honghuangdc** [comment]
这个问题倒没有遇到过，切换到node16版本试试

**Comment by honghuangdc** [comment]
看这个有没有帮助，https://blog.csdn.net/a772304419/article/details/122104917

**Comment by honghuangdc** [comment]
google搜索关键词 “Error: spawn xdg-open ENOENT”

**Comment by locustbaby** [comment]
解决了，感谢
