### ISSUE TITLE
[Bug]: PNPM安装依赖不成功的问题

### ISSUE THREAD

**Issue by redwolf1996** [honghuangdc/soybean-admin#211]
### 软件版本

main

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

pnpm install

### 期望的结果是什么？

顺利安装不报错

### 实际的结果是什么？

安装包的时候出错

### 日志记录（可选）

```golang
node_modules/vite-plugin-mock/node_modules/esbuild: Running postinstall script, failed in 103ms
.../node_modules/esbuild postinstall$ node install.js
│ node:internal/fs/utils:347
│     throw err;
│     ^
│ Error: EPERM: operation not permitted, open 'D:\code\lab\soybean-admin\node_modules\vite-plugin-mock\node_modules\esbuild\bin\esbuild'
│     at Object.openSync (node:fs:590:3)
│     at Object.writeFileSync (node:fs:2202:35)
│     at installWithWrapper (D:\code\lab\soybean-admin\node_modules\vite-plugin-mock\node_modules\esbuild\install.js:200:6)
│     at installOnWindows (D:\code\lab\soybean-admin\node_modules\vite-plugin-mock\node_modules\esbuild\install.js:225:3)
│     at Object.<anonymous> (D:\code\lab\soybean-admin\node_modules\vite-plugin-mock\node_modules\esbuild\install.js:246:3)
│     at Module._compile (node:internal/modules/cjs/loader:1191:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
│     at Module.load (node:internal/modules/cjs/loader:1069:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
│   errno: -4048,
│   syscall: 'open',
│   code: 'EPERM',
│   path: 'D:\\code\\lab\\soybean-admin\\node_modules\\vite-plugin-mock\\node_modules\\esbuild\\bin\\esbuild'
│ }
└─ Failed in 103ms at D:\code\lab\soybean-admin\node_modules\vite-plugin-mock\node_modules\esbuild
 ELIFECYCLE  Command failed with exit code 1.
```

### 补充说明（可选）

最新的main分支 用pnpm安装依赖出错
node 版本 v18.15.0
pnpm 版本 v8.1.1

**Comment by honghuangdc** [comment]
Error: EPERM: operation not permitted，这里是说没有权限，你用管理员模式打开终端，再安装试试

**Comment by redwolf1996** [comment]
> 
![image](https://user-images.githubusercontent.com/9690393/230803222-1587653a-d87c-4eb8-901e-9baa48e1944f.png)
额 我换了powershell和cmd（管理员模式）还有gitbash 好像都是这个错，node我换成v16了，然后把pnpm的版本从8.x换成7.x的最新版本也不行........都是报那个esbuild的问题，不知道什么原因，node和pnpm的版本需要和你的一致吗

**Comment by redwolf1996** [comment]
> 

用yarn就没有问题顺利安装
![image](https://user-images.githubusercontent.com/9690393/230806281-b8a6e6c4-fa4e-48c2-8716-389b4033bae3.png)

**Comment by honghuangdc** [comment]
自己环境的问题，自己排查一下吧
