### ISSUE TITLE
最新版会报 Cannot find module @rollup/rollup-win32-x64-msvc

### ISSUE THREAD

**Issue by hq520it** [honghuangdc/soybean-admin#308]
Error: Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (E:\vue_project\soybean-admin\node_modules\.pnpm\rollup@4.9.6\node_modules\rollup\dist\native.js:87:9)
    at Object.<anonymous> (E:\vue_project\soybean-admin\node_modules\.pnpm\rollup@4.9.6\node_modules\rollup\dist\native.js:96:48)
    ... 2 lines matching cause stack trace ...
    at require$$0.Module._extensions..js (E:\vue_project\soybean-admin\.pnp.cjs:17304:33)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at require$$0.Module._load (E:\vue_project\soybean-admin\.pnp.cjs:17152:31)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  [cause]: Error: Your application tried to access @rollup/rollup-win32-x64-msvc, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

  Required package: @rollup/rollup-win32-x64-msvc (via "@rollup\rollup-win32-x64-msvc")
  Required by: E:\vue_project\soybean-admin\node_modules\.pnpm\rollup@4.9.6\node_modules\rollup\dist\

**Comment by hq520it** [comment]
pnpm add 这个包后，提示安装成功，但pnpm dev还是会报错，win10系统

**Comment by honghuangdc** [comment]
1. 执行pnpm cleanup
2. pnpm i

**Comment by lvjiaxuan** [comment]
> 1. 执行pnpm cleanup
> 2. pnpm i

没有 cleanup command

**Comment by honghuangdc** [comment]
> > 1. 执行pnpm cleanup
> > 2. pnpm i
> 
> 没有 cleanup command

package.json 的 scripts 里面的cleanup命令，用npm执行得 `npm run cleanup`

**Comment by honghuangdc** [comment]
> > > 1. 执行pnpm cleanup
> > > 2. pnpm i
> > 
> > 
> > 没有 cleanup command
> 
> package.json 的 scripts 里面的cleanup命令，用npm执行得 `npm run cleanup`

前提条件是依赖已将安装好了
