### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by dargon5210** [honghuangdc/soybean-admin#43]
项目启动报
html = await server.transformIndexHtml?.(url, html, req.originalUrl);
                                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\workspace\2022\synway\soybean-admin\vite.config.ts:43:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.require.extensions.<computed> [as .ts] (E:\workspace\2022\synway\soybean-admin\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:71391:20)

**Comment by dargon5210** [comment]
不行 node是12.20.0的版本  这个语法不支持不应该，很奇怪

**Comment by honghuangdc** [comment]
或者升级一下node试试看

**Comment by dargon5210** [comment]
需要把node升级到14以上才可以
